### ISSUE TITLE
Join Hacktoberfest by adding it as a label to the repo

### ISSUE THREAD

**Issue by sandboxcode** [Akkudoktor-EOS/EOS#118]
### Proposed implementation

Add `hacktoberfest` as a label to the repo.

Why does it makes sense? It encourages developers to work actively on participating and open source repositories.
More details can be found at the [official hacktoberfest homepage](https://hacktoberfest.com/participation/#contributors).

This is an example of the freeCodeCamp repo that has the label added. Without the added label no rewards are associated to the users opening meaningful pull requests.

<img width="956" alt="image" src="https://github.com/user-attachments/assets/e2cd554d-f41c-485d-b93c-8502f74f537e">

**Comment by fortrieb** [comment]
Should identify some simple issue that can be labeled with _hacktoberfest_.

**Comment by drbacke** [comment]
How about this one ^^

**Comment by danimo** [comment]
From experience, Hacktoberfest tags mostly incentivize trophy seekers that care more about badges than quality. This gets to to the point where the Hacktoberfest website now desperately point out that they really are looking for *quality* submissions. Yet, the burden to decide what's quality and what's nonsense (anything from silly simple text reformatting to plain incorrect changes) still single-handedly falls to maintainers. Having made those experiences, I'd vote to stay out of Hacktoberfest for now.

**Comment by michaelosthege** [comment]
I agree with @danimo cause we've seen similar things in advance of Google Summer of Code over in the PyMC project.

If participation in Hacktoberfest is a priority for you, we should definitely raise the bar for contributions:
* Requiring more detailed ticket or discussion contributions
* Much stricter requirements for PRs
* Requiring >90 % test coverage for code changes

IMO the project needs contributions from experienced developers until the code structure and architecture stabilizes.

**Comment by drbacke** [comment]
No its Not, lets Close that.
