### ISSUE TITLE
Wärmepumpe allgemeinerer Ansatz

### ISSUE THREAD

**Issue by drbacke** [Akkudoktor-EOS/EOS#12]
Bisher ist ein sehr einfaches Wärmepumpen Modell unter modules\class_heatpump.py  und im EMS (class_ems.py) integriert. 
Aktuell ist es sogar ausgeschaltet und wird über die Standardlasten prognostiziert. 
Falls eine Steuerung der WP über das EOS vorgenommen werden soll, muss es aus den Last-Prognosen entfernt werden. 
Ansonsten würde die Last inklusive Wärmepumpe von der Lastprognose vorhergesagt werden und danach durch die EOS Planung nochmal. 
Todos: Besseres WP Modell / Lastprognose entprechend anpassen

**Comment by rschueler** [comment]
Es scheint, dass das aktuelle Modell für Wärmepumpen nur für Luft-Luft-Wärmepumpen geeignet ist, bei denen die Leistungsaufnahme direkt von der Temperatur abhängt. 

Für Luft-Wasser-Wärmepumpen, die einen Speicher beinhalten, wäre ein komplexeres Modell erforderlich. Möglicherweise müsste hierfür eine spezielle Simulation des Wärme-Kreislaufs erstellt werden, die Speicher, Verluste und eine Wärme-Lastprognose berücksichtigt.

**Comment by drbacke** [comment]
Es sollten hier am besten verschiedene Wärmepumpenmodelle vorgesehen werden.
