### ISSUE TITLE
[BUG]: PyPi Integration Bug: flask Server data

### ISSUE THREAD

**Issue by drbacke** [Akkudoktor-EOS/EOS#121]
### Describe the issue:

flask_severy.py      
gesamtlast_simple, database path (/data) not working anymore:
file_path = os.path.join("data", "load_profiles.npz")

### Reproduceable code example:

```python
start flask_server.py
call:
http://127.0.0.1:8503/gesamtlast_simple?year_energy=2000&
```

### Error message:

```shell
TypeError: 'NoneType' object is not subscriptable
```

### Version information:

-

**Comment by b0661** [comment]
@drbacke where shall the static data reside?

Shall it become part of the EOS library package or shall it become part of the server package?

**Comment by drbacke** [comment]
Its used in the library for load prediction.
The Call is in the server

**Comment by b0661** [comment]
I just added a pull request. Moved the data to the server package.

If the data is default data for the EOS library it may better be integrated in the library. In this case one of the classes in the library should provide access to the data. Just my 2c.

For now it is working. 

Using 
``
start flask_server.py; call: http://127.0.0.1:8503/gesamtlast_simple?year_energy=2000&
``
as a test would be fine.
