### ISSUE TITLE
[BUG]: class_ems  np.zero for all arrays

### ISSUE THREAD

**Issue by drbacke** [Akkudoktor-EOS/EOS#132]
### Describe the issue:

This is a bad idea, as the first value has to be skipped in part so that the times are correct.
However, 0 is a valid load value. 

### Version information:

-

**Comment by NormannK** [comment]
that is exactly what i asked in the PR and assumed.
https://github.com/Akkudoktor-EOS/EOS/pull/103#issuecomment-2395217387

I suggest I change the first values to `None` just before returning it and add that to the explanation of the parameters in in the readme
