### ISSUE TITLE
More UnitTests - The Code has now many bugs

### ISSUE THREAD

**Issue by drbacke** [Akkudoktor-EOS/EOS#133]
### Description

I currently have to permanently remove errors from the code that were added by PRs. I also currently have great doubts that the entire calculation is still correct. Maybe a bigger revert is neccessary. 
We urgently need more unit tests,

**Comment by b0661** [comment]
Added PR #135 to test the server. Needs PR #125 to pass the tests. Fails currently - which is the proper result.
