### ISSUE TITLE
[BUG]: Readme out of date?

### ISSUE THREAD

**Issue by Isengo1989** [Akkudoktor-EOS/EOS#180]
### Describe the issue:

Trying to install by Readme but there seem to be files missing

### Version information:

There seems to be no config.py nor a ./flask_server.py

![image](https://github.com/user-attachments/assets/294516c5-5102-42da-94e4-89b4a989e42d)

**Comment by grossman87** [comment]
jooo, same problem here - would be great to update the README - I would be happy to try this system with my

PV / Battery / Wallbox / HeatPump / Tibber =)

**Comment by jadirc** [comment]
After git clone, try the Makefile with make install and make run. That did it for me.
