### ISSUE TITLE
[BUG]: ...ModuleNotFoundError

### ISSUE THREAD

**Issue by mazie-78** [Akkudoktor-EOS/EOS#201]
### Describe the issue:

The server does not start on a Raspi

### Reproduceable code example:

```python
I add this before line 24 in fastapi_server.py: 24 "from akkudoktoreos.class_load import LoadForecast"

"
pathstr= os.path.abspath(".")
path= '/'.join(pathstr.split('/')[:-1])
path= '/'.join(path.split('/')[:-1])
sys.path.append(path)
"
```
After that the server is online

### Error message:

```shell
File "/home/xxxxxxx/EOS/src/akkudoktoreos/server/fastapi_server.py", line 25, in <module>
    from akkudoktoreos.class_load import LoadForecast
ModuleNotFoundError: No module named 'akkudoktoreos'
```

### Version information:

Version from 15.11.24
Raspi 5 
Raspi OS

**Comment by Lasall** [comment]
How are you trying to start the server? If you start it from source code, use `fastapi run src/akkudoktoreos/server/fastapi_server.py`

**Comment by mazie-78** [comment]
python fastapi_server.py

**Comment by Lasall** [comment]
Please start it the recommended way

**Comment by NormannK** [comment]
anyway im trying to replicate the behavior. I can run the server using `python fastapi_server.py` without any problem. 
Is that Raspi specific?

**Comment by mazie-78** [comment]
I think so

**Comment by Lasall** [comment]
The error occurs when the package was not installed in the venv (pip install -e .). Also I realised the instructions were not up-to-date.
