### ISSUE TITLE
Aufgabe EMS und EOS

### ISSUE THREAD

**Issue by georg41980** [Akkudoktor-EOS/EOS#24]
Beim EOS ist es eine Optimierung anhand der Kosten, es geht darum alle Anforderungen mit der günstigen Lösung zu berechnen und auszuwählen, man kann nur etwas Einsparen, wenn es schaltbare Lasten gibt! Die Aufgabe vom EMS (Energie Management System)ist es, die schaltbaren Lasten zu aktiv zu managen, sodass Geräte ein und ausschaltet, je nachdem wie die aktuelle Situation ist. Dies muss in Sekunden passieren, damit man auf sich änderte, Bedienungen direkt reagieren kann(z. B. Wolke vor der Solaranlage springt die Leistung von 100 % auf 0 % in Sekunden. ) Bei ein und ausschalten von Solarspeicher, beim Laden des E-Autos, bei ein und ausschalten von Wärmepumpe. Dies sind Lasten, bei denen es nicht ausreicht, die nur ein paar mal in de stünde zu betrachten.  Hier muss man schauen, was bei jeder Berechnung zu beachten ist und welche es auch ausreicht, mit anderen Intervallen zu berechnen z.b. Minütlich, stündlich, täglich um eine Minimierung der Energiekosten zu haben ohne das sie zu großen Einfluss auf die Regelung haben und ohne den PC zu stark zu belasten.

**Comment by drbacke** [comment]
Ja genau, das EOS ist eher für eine mehrtätige Planung und die meisten EMS Systeme agieren im Sekunden / Minuten Bereich. Beides in Kombination wäre sehr sinnvoll.
Wobei ich das EMS Problem als wesentlich einfacher empfinde, hier reichen oftmals einfache Ansätze wie Überschussladen der Wallbox etc. 
Für die Suboptimierung sollte man sich, wenn man das will, einen anderen Ansatz überlegen. Dafür wird auch eine lineare Optimierung ausreichend sein, das ginge dann erheblich schneller.
