### ISSUE TITLE
Find a new default Port

### ISSUE THREAD

**Issue by danimo** [Akkudoktor-EOS/EOS#25]
Port 5000 is occupied on MacOS by default. Switch both the Flash and the docker ports to something else. As 8080 is often already occupied (and a well-known port for Proxies), I'd like to go for Port 3000.

**Comment by dsiebel** [comment]
3000 is already the default port for Grafana amongst others.
What about my proposal of using 8503? 😄

**Comment by dsiebel** [comment]
Note that port 3000 is the default port of Grafana (among others).
