### ISSUE TITLE
Dependencies aufräumen

### ISSUE THREAD

**Issue by njoerd114** [Akkudoktor-EOS/EOS#4]
In einigen Klassen werden Dependencies geladen, die aber nirgends verwendet werden.

**Comment by njoerd114** [comment]
evtl. sollten wir auch gucken, dass wir uns dependabot reinholen, um dependencies zu managen.

**Comment by NormannK** [comment]
would be done with #73 and #74

**Comment by noootch** [comment]
Hi,
bei Interesse würde ich mich anbieten, ein modernes Dependency-Management mit poetry umzusetzen.
Grüße
Chris
