### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by drbacke** [Akkudoktor-EOS/EOS#56]
Kritische parts während der Optimierung: 
Vektorisierungen + Pandas (iloc besonders) aus den kritischen parts entfernen

**Comment by NormannK** [comment]
ich habe mal etwas mit der class_optimize rumgespielt. mit der test.py und nem fixed seed. Bei mir ist es ca 50% schneller. Da ist aber noch ne ganze ecke zu holen. 

`import os
import sys
import random
from datetime import datetime

import numpy as np

from deap import base, creator, tools, algorithms

from modules.class_akku import PVAkku
from modules.class_ems import EnergieManagementSystem
from modules.class_haushaltsgeraet import Haushaltsgeraet
from modules.class_inverter import Wechselrichter
from config import *
from modules.visualize import visualisiere_ergebnisse

# Add the parent directory to sys.path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

class optimization_problem:
    def __init__(self, prediction_hours=48, strafe=10, optimization_hours=24, verbose=False, fixed_seed = None):
        self.prediction_hours = prediction_hours
        self.strafe = strafe
        self.opti_param = None
        self.fixed_eauto_hours = prediction_hours - optimization_hours
        self.possible_charge_values = moegliche_ladestroeme_in_prozent
        self.verbose = verbose
        if fixed_seed is not None:
            random.seed(fixed_seed)

    def split_individual(self, individual):
        """
        Splits the given individual into the following parameters:
        - Discharge parameters (discharge_hours_bin)
        - Charge parameters (eautocharge_hours_float)
        - Household devices (spuelstart_int, if applicable)
        """
        # Extract discharge and charge parameters directly from the individual
        discharge_hours_bin = individual[:self.prediction_hours]  # First 24 values are Booleans (discharging)
        eautocharge_hours_float = individual[self.prediction_hours:self.prediction_hours * 2]  # Next 24 values are floats (charging)

        spuelstart_int = None
        if self.opti_param and self.opti_param.get("haushaltsgeraete", 0) > 0:
            spuelstart_int = individual[-1]  # Last value is the start time for household devices

        return discharge_hours_bin, eautocharge_hours_float, spuelstart_int

    def setup_deap_environment(self, opti_param, start_hour):
        """
        Sets up the DEAP environment for genetic optimization, registering
        fitness, individual creation, mutation, and selection mechanisms.
        """
        self.opti_param = opti_param

        # Remove previously created types in DEAP if they exist
        if "FitnessMin" in creator.__dict__:
            del creator.FitnessMin
        if "Individual" in creator.__dict__:
            del creator.Individual

        # Create new types for fitness and individuals
        creator.create("FitnessMin", base.Fitness, weights=(-1.0,))
        creator.create("Individual", list, fitness=creator.FitnessMin)

        # Define toolbox parameters
        self.toolbox = base.Toolbox()
        self.toolbox.register("attr_bool", random.randint, 0, 1)
        self.toolbox.register("attr_float", random.uniform, 0, 1)  # For continuous values between 0 and 1 (e.g., EV charge power)
        # self.toolbox.register("attr_choice", random.choice, self.possible_charge_values)  # For discrete charge levels
        self.toolbox.register("attr_int", random.randint, start_hour, 23)

        # Household appliances setup
        if opti_param["haushaltsgeraete"] > 0:
            def create_individual():
                attrs = [self.toolbox.attr_bool() for _ in range(self.prediction_hours)]  # 24 bools for discharge
                attrs += [self.toolbox.attr_float() for _ in range(self.prediction_hours)]  # 24 floats for charging
                attrs.append(self.toolbox.attr_int())  # Start time for household devices
                return creator.Individual(attrs)
        else:
            def create_individual():
                attrs = [self.toolbox.attr_bool() for _ in range(self.prediction_hours)]  # 24 bools for discharge
                attrs += [self.toolbox.attr_float() for _ in range(self.prediction_hours)]  # 24 floats for charging
                return creator.Individual(attrs)

        # Register creation, mating, mutation, and selection functions in DEAP's toolbox
        self.toolbox.register("individual", create_individual)
        self.toolbox.register("population", tools.initRepeat, list, self.toolbox.individual)
        self.toolbox.register("mate", tools.cxTwoPoint)
        self.toolbox.register("mutate", tools.mutFlipBit, indpb=0.1)
        # self.toolbox.register("mutate", mutate_choice, self.possible_charge_values, indpb=0.1)
        # self.toolbox.register("mutate", tools.mutUniformInt, low=0, up=len(self.possible_charge_values)-1, indpb=0.1)
        self.toolbox.register("select", tools.selTournament, tournsize=3)

    def evaluate_inner(self, individual, ems, start_hour):
        """
        Internal evaluation function: applies the individual's parameters to the EMS and runs a simulation.
        """
        ems.reset()
        discharge_hours_bin, eautocharge_hours_float, spuelstart_int = self.split_individual(individual)

        # Set household devices start time if applicable
        if self.opti_param["haushaltsgeraete"] > 0:
            ems.set_haushaltsgeraet_start(spuelstart_int, global_start_hour=start_hour)

        # Set battery discharge schedule
        ems.set_akku_discharge_hours(discharge_hours_bin)

        # Disable eautocharge for the last 'x' hours
        start_fixed_hours = self.prediction_hours - self.fixed_eauto_hours
        eautocharge_hours_float[start_fixed_hours:self.prediction_hours] = [0.0] * (self.fixed_eauto_hours)

        # Set EV charging schedule
        ems.set_eauto_charge_hours(eautocharge_hours_float)

        # Run simulation
        return ems.simuliere(start_hour)

    def evaluate(self, individual, ems, parameter, start_hour, worst_case):
        """
        Fitness function that evaluates the given individual by applying it to the EMS and calculating penalties and rewards.
        """
        try:
            evaluation_results = self.evaluate_inner(individual, ems, start_hour)
        except Exception:
            return (100000.0,)

        # Calculate total balance in euros
        gesamtbilanz = evaluation_results["Gesamtbilanz_Euro"]
        if worst_case:
            gesamtbilanz *= -1.0

        discharge_hours_bin, eautocharge_hours_float, spuelstart_int = self.split_individual(individual)
        max_ladeleistung = np.max(self.possible_charge_values)

        # Calculate penalties
        strafe_ueberschreitung = self.calculate_exceeding_penalty(eautocharge_hours_float, max_ladeleistung)
        gesamtbilanz += self.calculate_unused_discharge_penalty(discharge_hours_bin)
        gesamtbilanz += self.calculate_restricted_charging_penalty(eautocharge_hours_float, parameter)

        # Check minimum state of charge (SoC) for the EV
        final_soc = ems.eauto.ladezustand_in_prozent()
        if (parameter['eauto_min_soc'] - final_soc) > 0.0:
            gesamtbilanz += self.calculate_min_soc_penalty(eautocharge_hours_float, parameter, final_soc)

        # Record extra data for the individual
        eauto_roi = parameter['eauto_min_soc'] - final_soc
        individual.extra_data = (evaluation_results["Gesamtbilanz_Euro"], evaluation_results["Gesamt_Verluste"], eauto_roi)

        # Calculate residual energy in the battery
        restenergie_akku = ems.akku.aktueller_energieinhalt()
        restwert_akku = restenergie_akku * parameter["preis_euro_pro_wh_akku"]

        # Final penalties and fitness calculation
        strafe = max(0, (parameter['eauto_min_soc'] - final_soc) * self.strafe)
        gesamtbilanz += strafe - restwert_akku + strafe_ueberschreitung

        return (gesamtbilanz,)


    def calculate_exceeding_penalty(self, eautocharge_hours_float, max_ladeleistung):
        """Calculate penalties for exceeding charging power limits."""
        penalty = 0.0
        for ladeleistung in eautocharge_hours_float:
            if ladeleistung > max_ladeleistung:
                penalty += self.strafe * 10  # Penalty is proportional to the violation
        return penalty

    def calculate_unused_discharge_penalty(self, discharge_hours_bin):
        """Calculate penalty for unused discharge hours."""
        penalty = 0.0
        for hour in discharge_hours_bin:
            if hour == 0.0:
                penalty += 0.01  # Small penalty for each unused discharge hour
        return penalty

    def calculate_restricted_charging_penalty(self, eautocharge_hours_float, parameter):
        """Calculate penalty for charging the EV during restricted hours."""
        penalty = 0.0
        for i in range(self.prediction_hours - self.fixed_eauto_hours, self.prediction_hours):
            if eautocharge_hours_float[i] != 0.0:
                penalty += self.strafe  # Penalty for charging during fixed hours
        return penalty

    def calculate_min_soc_penalty(self, eautocharge_hours_float, parameter, final_soc):
        """Calculate penalty for not meeting the minimum state of charge (SoC)."""
        penalty = 0.0
        for hour in eautocharge_hours_float:
            if hour != 0.0:
                penalty += self.strafe  # Penalty for not meeting minimum SoC
        return penalty
    # Genetic Algorithm for Optimization
    
    def optimize(self, start_solution=None):
        """
        Runs the genetic algorithm to optimize the solution.
        :param start_solution: Optional starting solution to inject into the population.
        :return: Best solution (hall of fame) and member statistics.
        """
        population = self.toolbox.population(n=300)
        hof = tools.HallOfFame(1)  # Hall of Fame to store the best solution
        
        # Statistics object to track the optimization progress
        stats = tools.Statistics(lambda ind: ind.fitness.values)
        stats.register("avg", np.mean)
        stats.register("min", np.min)
        stats.register("max", np.max)
        
        if self.verbose:
            print("Start solution:", start_solution)

        # Inject starting solution into population if provided
        if start_solution is not None and start_solution != -1:
            starting_individual = creator.Individual(start_solution)
            population = [starting_individual] * 3 + population  # Insert the starting solution three times

        # Execute the genetic algorithm (Mu + Lambda strategy)
        algorithms.eaMuPlusLambda(
            population, self.toolbox,
            mu=100, lambda_=400,
            cxpb=0.5, mutpb=0.3,
            ngen=100, stats=stats,
            halloffame=hof, verbose=self.verbose
        )

        # Collect extra data (if exists) from the individuals in the population
        member = {"bilanz": [], "verluste": [], "nebenbedingung": []}
        for ind in population:
            if hasattr(ind, 'extra_data'):
                member["bilanz"].append(ind.extra_data[0])
                member["verluste"].append(ind.extra_data[1])
                member["nebenbedingung"].append(ind.extra_data[2])

        return hof[0], member

    def optimierung_ems(self, parameter=None, start_hour=None, worst_case=False, startdate=None):
        """
        Main EMS (Energy Management System) optimization function.
        Initializes various system components like PV forecast, battery, and household devices.
        Runs the optimizer and visualizes results.

        :param parameter: Dictionary containing all necessary system parameters
        :param start_hour: Starting hour for the simulation
        :param worst_case: Flag to handle worst-case scenario optimization
        :param startdate: Optional start date for simulation
        :return: Dictionary with optimization results
        """
        # Set date ranges for prediction based on start date or current date
        current_date = datetime.now()
        if startdate is None:
            date = (current_date.date() + timedelta(hours=self.prediction_hours)).strftime("%Y-%m-%d")
            date_now = current_date.strftime("%Y-%m-%d")
        else:
            date = (startdate + timedelta(hours=self.prediction_hours)).strftime("%Y-%m-%d")
            date_now = startdate.strftime("%Y-%m-%d")

        # Initialize key parameters for the optimization process
        akku_size = parameter['pv_akku_cap']  # Battery capacity (Wh)
        einspeiseverguetung_euro_pro_wh = np.full(self.prediction_hours, parameter["einspeiseverguetung_euro_pro_wh"])  # Feed-in tariff (Euro / Wh)

        # Create battery and electric vehicle objects
        akku = PVAkku(kapazitaet_wh=akku_size, hours=self.prediction_hours, start_soc_prozent=parameter["pv_soc"], max_ladeleistung_w=5000)
        discharge_array = np.ones(self.prediction_hours)  # Array defining discharge schedule
        akku.set_charge_per_hour(discharge_array)

        laden_moeglich = np.ones(self.prediction_hours)  # Array defining charging schedule
        eauto = PVAkku(
            kapazitaet_wh=parameter["eauto_cap"],
            hours=self.prediction_hours,
            lade_effizienz=parameter["eauto_charge_efficiency"],
            entlade_effizienz=1.0,
            max_ladeleistung_w=parameter["eauto_charge_power"],
            start_soc_prozent=parameter["eauto_soc"]
        )
        eauto.set_charge_per_hour(laden_moeglich)

        # Minimum SOC for electric car and initial parameters
        min_soc_eauto = parameter['eauto_min_soc']
        start_params = parameter['start_solution']

        # Initialize household device if duration > 0
        spuelmaschine = None
        if parameter["haushaltsgeraet_dauer"] > 0:
            spuelmaschine = Haushaltsgeraet(
                hours=self.prediction_hours,
                verbrauch_kwh=parameter["haushaltsgeraet_wh"],
                dauer_h=parameter["haushaltsgeraet_dauer"]
            )
            spuelmaschine.set_startzeitpunkt(start_hour)

        # PV and Temperature Forecast
        pv_forecast = parameter['pv_forecast']
        temperature_forecast = parameter['temperature_forecast']

        # Electricity prices for the specified date
        specific_date_prices = parameter["strompreis_euro_pro_wh"]

        # Initialize components like inverter and EMS
        wr = Wechselrichter(10000, akku)  # Inverter initialization
        ems = EnergieManagementSystem(
            gesamtlast=parameter["gesamtlast"],
            pv_prognose_wh=pv_forecast,
            strompreis_euro_pro_wh=specific_date_prices,
            einspeiseverguetung_euro_pro_wh=einspeiseverguetung_euro_pro_wh,
            eauto=eauto,
            haushaltsgeraet=spuelmaschine,
            wechselrichter=wr
        )
        o = ems.simuliere(start_hour)

        # Initialize optimizer parameters
        opti_param = {"haushaltsgeraete": int(spuelmaschine is not None)}  # Use int conversion for boolean check

        self.setup_deap_environment(opti_param, start_hour)

        # Define evaluation wrapper for optimization
        def evaluate_wrapper(individual):
            """Wrapper for evaluating individuals."""
            return self.evaluate(individual, ems, parameter, start_hour, worst_case)

        # Register the evaluation function
        self.toolbox.register("evaluate", evaluate_wrapper)

        # Run optimization and obtain the initial solution
        start_solution, extra_data = self.optimize(start_params)
        best_solution = start_solution

        # Evaluate the best solution
        o = self.evaluate_inner(best_solution, ems, start_hour)

        # Process the best solution into relevant components
        eauto = ems.eauto.to_dict()
        discharge_hours_bin, eautocharge_hours_float, spuelstart_int = self.split_individual(best_solution)

        # Visualize the results (commented out for now)
        visualisiere_ergebnisse(parameter["gesamtlast"], pv_forecast, specific_date_prices, o, 
                                 discharge_hours_bin, eautocharge_hours_float, 
                                 temperature_forecast, start_hour, self.prediction_hours, 
                                 einspeiseverguetung_euro_pro_wh, extra_data=extra_data)
        #os.system("cp visualisierungsergebnisse.pdf ~/")  # Ensure compatibility with Windows

        # Return the final results of the simulation
        return {
            "discharge_hours_bin": discharge_hours_bin,
            "eautocharge_hours_float": eautocharge_hours_float,
            "result": o,
            "eauto_obj": eauto,
            "start_solution": best_solution,
            "spuelstart": spuelstart_int,
            "simulation_data": o
        }`

**Comment by drbacke** [comment]
Danke dir, ich habe es eingefügt und das sieht für mich gut aus. Ich würde den Issue dennoch offen lassen, da noch Vektorisierungen + Pandas überprüft werden muss. 
Aber guter Schritt, besonders die "toten" Parameter (Haushaltsgeräte)
