### ISSUE TITLE
Automatisierte Tests

### ISSUE THREAD

**Issue by njoerd114** [Akkudoktor-EOS/EOS#6]
Wir sollten uns überlegen, welche automatisierten Tests wir für die Klassen definieren wollen.

Für den Anfang würde ich Snapshot Tests vorschlagen.

**Comment by danimo** [comment]
Reminder: Sobald es Tests gibt, sollten die für jeden PR laufen. Das ist dann auch der Zeitpunkt, wo wir direkte Pushes nach main per Policy und via Branch Protection unterbinden sollten.

**Comment by drbacke** [comment]
Erste Tests sind integriert. Müsste jetzt noch automatisiert werden und die Tests dann ausgeweitet.
