### ISSUE TITLE
Setup containerisieren

### ISSUE THREAD

**Issue by njoerd114** [Akkudoktor-EOS/EOS#7]
Es wäre wünschenswert, das Projekt als Docker-Image zur Verfügung zu stellen und eine Anleitung (bspw. per docker-compose.yaml) zu geben, um das Projekt inkl. Abhängigkeiten Plattform-Unabhängig zu starten.

**Comment by dsiebel** [comment]
@njoerd114 @drbacke kann ich mich gerne drum kümmern

**Comment by danimo** [comment]
@dsiebel Super! Schicke gerne einen PR. Ich kann falls nötig noch Dinge in den Projekt-Settings freischalten.

**Comment by dsiebel** [comment]
> * multi-platform
Hatte in erster Linie vor das ganze in eine `docker-compose.yaml` zu kippen.
Multi-arch wäre dadurch gegeben, dass das ganze da gebaut wird wo es auch läuft:
`docker compose up --build`

> * distroless?
Nicht unmöglich, aber reichlich schwierig umzusetzen für Python.

PR is allerdings schon fertig, habe die Kommentare hier erst jetzt gesehen.
https://github.com/Akkudoktor-EOS/EOS/pull/11

Konnte noch nicht verifizieren, dass das ganze so auch funktioniert, API-wise.

**Comment by danimo** [comment]
Ich denke das `docker-compose.yml` ist für den ersten Aufschlag ok. Sobald wir Releases bauen, können wir fertige Pakete, auch multi-Platform, per CI bauen lassen und publisen.

**Comment by dsiebel** [comment]
Ich denke, der hier kann nun geschlossen werden?

**Comment by danimo** [comment]
Ja, die MacOS Port-Geschichte sollten wir nicht in Docker lösen, sondern durchgehnd. Dafür mache ich ein separates issue auf.
