### ISSUE TITLE
README-DE.md line 110 not a date

### ISSUE THREAD

**Issue by simcup** [Akkudoktor-EOS/EOS#82]
moin, ich kann mir vorstellen das in der readme an zeile 110 (Input für den Flask Server ) der 30.07.2024 stehen soll, finde aber auch ein pullrequest für einen typo an nicht kritischer stelle ist overkill. kthybye

**Comment by drbacke** [comment]
Gerne fixen, erstelle einen PR und los 👍

**Comment by sandboxcode** [comment]
Würde den fix eben in nem Branch publishen und den PR erstellen. Geht aber ohne Contributor-Rolle nicht, oder @drbacke ? Würdest du mir die Rolle eben assignen bzw. das ausreichende Rechteprofil?

**Comment by drbacke** [comment]
Müsste geht gehen, das repo ist offen

**Comment by sandboxcode** [comment]
Tatsächlich nicht möglich, kann meinen Branch nicht ins origin repo pushen. Nur als fork, aber das wird das origin repo nicht erkennen denke ich. 
<img width="316" alt="image" src="https://github.com/user-attachments/assets/9bbd4b98-1d3d-42f1-8446-3b5a50c74e05">

**Comment by drbacke** [comment]
Thats the normal way to do this.
Fork -> PR

**Comment by sandboxcode** [comment]
Auch das wird leider irgendwie nicht zugelassen.

<img width="522" alt="image" src="https://github.com/user-attachments/assets/c01e0d46-2a41-4f48-a1fa-67868ce46017">

Was mache ich falsch? Habe meinen Branch im Fork gepushed, aber Commit History wird vermutlich nicht mitgepullt?

Vielleicht stelle ich mich auch doof an, aber bisher habe ich immer nur in eigenen Repos der Branches gearbeitet und PRs erstellt.

<img width="1216" alt="image" src="https://github.com/user-attachments/assets/0a3b4003-61cd-47f3-803f-da1ce10dbb28">

**Comment by sandboxcode** [comment]
Falls jemand aufs gleiche Problem stoßen sollte in der Zukunft: Problem war bei mir einfach über `git rebase upstream/main` zu lösen, da das die commit histories des forks mit dem origin main wieder angleicht.
