### ISSUE TITLE
TODOs aus der README.md hierhin übertragen

### ISSUE THREAD

**Issue by danimo** [Akkudoktor-EOS/EOS#9]
Die [README.md](https://github.com/Akkudoktor-EOS/EOS?tab=readme-ov-file#todo) hat einige nur grob angerissene TODOs. Diese müssen als actionable Issue hier ausformuliert und dann aus der README.md gelöscht werden.

**Comment by lorenzleutgeb** [comment]
Labels basierend auf `README.md` angelegt: frontend, backend, simulation, optimization

**Comment by drbacke** [comment]
Das werde ich gerne erledigen.
