### ISSUE TITLE
Pre Commit to restrictive

### ISSUE THREAD

**Issue by drbacke** [Akkudoktor-EOS/EOS#92]
Local checks with ruff passed, with pre commit = Fail

**Comment by michaelosthege** [comment]
The merge of #91 included some changes to which pre-commit was not applied. The check was also :x: in that PR, by the way. Under "Branch protection rules" you can require PRs to have passing ✔️ checks before merging:

![image](https://github.com/user-attachments/assets/28493c0f-12b7-4fa5-9f74-9cd6bfbfd09b)

![image](https://github.com/user-attachments/assets/4c3925e5-d577-42ec-b676-f05815f9ccfa)

This would help to prevent accidentally merging PRs that break code style or tests.

**Comment by drbacke** [comment]
Yes, I know that, but I thought that ruff counted as standard here. And code that conforms to ruff is not accepted. That seems a bit too restrictive to me

**Comment by michaelosthege** [comment]
Can you give an example?
Maybe we have OS-dependent effects?
I'm on Windows and the checks pass locally and in CI, so for current `main` I don't see issues.

**Comment by michaelosthege** [comment]
On 0th indentation level both `ruff format .` and `pre-commit run --all` format this as 👇 on my machine

```python
assert (
    len(result["Netzbezug_Wh_pro_Stunde"]) == 47
), "The length of 'Netzbezug_Wh_pro_Stunde' should be 48."
```

`ruff check .` only runs the linter and reports `All checks passed!` regardless of the format.

**Comment by drbacke** [comment]
I use pre commit on my local system now. It was Not the ruff Check.
Lets Close this.
